using System.Security.Cryptography;
using System.Text;
using OptimizeAll.SharedKernel.Guards;
using OptimizeAll.SharedKernel.Primitives;

namespace OptimizeAll.Domain.Governance;

/// <summary>
/// A SHA-256 digest of the canonical form of a payload, binding an approval to exactly the bytes
/// that will execute.
/// <para>
/// The attack this prevents is time-of-check/time-of-use substitution: an approver reviews payload
/// A, and payload B — perhaps regenerated by the same agent, perhaps not — executes. Comparing
/// fingerprints at execution time makes that substitution fail closed.
/// </para>
/// </summary>
public sealed class PayloadFingerprint : ValueObject
{
    public const int HexLength = 64;

    private PayloadFingerprint(string value) => Value = value;

    /// <summary>Lower-case hexadecimal SHA-256 digest.</summary>
    public string Value { get; }

    /// <summary>Computes the fingerprint of a JSON payload. Throws when the payload is not valid JSON.</summary>
    public static PayloadFingerprint Compute(string json)
    {
        string canonical = CanonicalJson.Canonicalise(json);
        byte[] digest = SHA256.HashData(Encoding.UTF8.GetBytes(canonical));
        return new PayloadFingerprint(Convert.ToHexStringLower(digest));
    }

    /// <summary>Rehydrates a stored fingerprint.</summary>
    public static PayloadFingerprint FromHex(string value)
    {
        Ensure.NotNullOrWhiteSpace(value);

        string normalised = value.Trim().ToLowerInvariant();

        if (normalised.Length != HexLength || !normalised.All(char.IsAsciiHexDigitLower))
        {
            throw new ArgumentException(
                $"A payload fingerprint must be {HexLength} lower-case hexadecimal characters.",
                nameof(value));
        }

        return new PayloadFingerprint(normalised);
    }

    /// <summary>
    /// Constant-time comparison. The timing signal here is small, but a fingerprint check is exactly
    /// the kind of comparison where a fixed-cost implementation removes a whole class of question.
    /// </summary>
    public bool Matches(PayloadFingerprint other)
    {
        ArgumentNullException.ThrowIfNull(other);

        return CryptographicOperations.FixedTimeEquals(
            Encoding.ASCII.GetBytes(Value),
            Encoding.ASCII.GetBytes(other.Value));
    }

    public override string ToString() => Value;

    protected override IEnumerable<object?> GetEqualityComponents()
    {
        yield return Value;
    }
}
