// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OptimizeAll.Infrastructure.Persistence;
using Pgvector;

#nullable disable

namespace OptimizeAll.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OptimizeAllDbContext))]
    partial class OptimizeAllDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OptimizeAll.Domain.Access.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean")
                        .HasColumnName("is_builtin");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.PrimitiveCollection<HashSet<string>>("_permissions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("permissions");

                    b.HasKey("Id");

                    b.HasIndex("TenantIdentifier", "Key")
                        .IsUnique();

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Access.RoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Environment")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid")
                        .HasColumnName("principal_id");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("principal_type");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantIdentifier", "PrincipalId");

                    b.HasIndex("PrincipalId", "RoleId", "WorkspaceId", "Environment")
                        .IsUnique();

                    b.ToTable("role_assignment", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Access.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("ExternalSubject")
                        .HasMaxLength(255)
                        .IsUnicode(true)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_subject");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantIdentifier", "Email")
                        .IsUnique();

                    b.HasIndex("TenantIdentifier", "ExternalSubject")
                        .IsUnique()
                        .HasFilter("external_subject IS NOT NULL");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.AgentCatalog.AgentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_key");

                    b.Property<Guid?>("ApprovalPolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("approval_policy_id");

                    b.Property<string>("BudgetPolicy")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("budget_policy");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("integer")
                        .HasColumnName("definition_version");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("MaxRiskClass")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("max_risk_class");

                    b.Property<string>("MemoryPolicy")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("memory_policy");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("mission");

                    b.Property<string>("ModelPolicy")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("model_policy");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("text")
                        .HasColumnName("system_prompt");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "AgentKey", "DefinitionVersion")
                        .IsUnique();

                    b.HasIndex("WorkspaceId", "AgentKey", "Status");

                    b.ToTable("agent_definition", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("actor_type");

                    b.Property<string>("AfterStateJson")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("after_state");

                    b.Property<string>("BeforeStateJson")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("before_state");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EntryHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character(64)")
                        .HasColumnName("entry_hash")
                        .IsFixedLength();

                    b.Property<string>("Environment")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(true)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character(64)")
                        .HasColumnName("previous_hash")
                        .IsFixedLength();

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("TenantIdentifier", "OccurredAt");

                    b.HasIndex("TenantIdentifier", "Sequence")
                        .IsUnique();

                    b.HasIndex("TenantIdentifier", "Action", "OccurredAt");

                    b.ToTable("audit_event", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Execution.AgentMemoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_key");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<float>("Importance")
                        .HasColumnType("real")
                        .HasColumnName("importance");

                    b.Property<string>("Outcome")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("outcome_signal");

                    b.Property<Guid?>("SourceRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_run_id");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "AgentKey", "Environment", "Tier");

                    b.ToTable("agent_memory_entry", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Execution.AgentRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_definition_id");

                    b.Property<string>("AgentKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("agent_key");

                    b.Property<Guid?>("BlockingApprovalId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocking_approval_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<string>("ErrorJson")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("error");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("input");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("boolean")
                        .HasColumnName("is_dry_run");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseHolder")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lease_holder");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("OutputJson")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("output");

                    b.Property<string>("Provider")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("trigger_type");

                    b.Property<Guid?>("TriggeredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("triggered_by");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("WorkspaceId", "Status", "LeaseExpiresAt");

                    b.ToTable("agent_run", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Governance.ApprovalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Key")
                        .IsUnique();

                    b.ToTable("approval_policy", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Governance.ApprovalRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgentRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_run_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("PayloadFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("payload_hash")
                        .IsFixedLength();

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by_principal");

                    b.Property<string>("RequestedByType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("requested_by_type");

                    b.Property<int>("RequiredApproverCount")
                        .HasColumnType("integer")
                        .HasColumnName("required_approver_count");

                    b.Property<string>("RequiredRoleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("required_role_key");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("RiskClass")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("risk_class");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<Guid?>("ToolInvocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("tool_invocation_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("AgentRunId");

                    b.HasIndex("WorkspaceId", "Environment", "Status", "ExpiresAt");

                    b.ToTable("approval_request", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Insights.KpiSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<string>("DimensionsJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("dimensions");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<string>("Granularity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("granularity");

                    b.Property<string>("KpiKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("kpi_key");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<decimal>("Value")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("value");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Environment", "KpiKey", "PeriodStart", "Granularity");

                    b.ToTable("kpi_snapshot", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Knowledge.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .IsUnicode(true)
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer")
                        .HasColumnName("token_count");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("WorkspaceId", "Environment");

                    b.ToTable("knowledge_chunk", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Knowledge.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(true)
                        .HasColumnType("character(64)")
                        .HasColumnName("content_hash")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset?>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<string>("SourceUri")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_uri");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(true)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Environment", "ContentHash")
                        .IsUnique();

                    b.ToTable("knowledge_document", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("link_url");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("severity");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId", "ReadAt", "CreatedAt");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Notifications.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.HasIndex("TenantIdentifier", "MessageType", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Orchestration.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("ObjectivePayloadJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("objective_payload");

                    b.Property<string>("ObjectiveTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("objective_title");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("WorkspaceId", "Status");

                    b.ToTable("workflow_run", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Scheduling.ScheduleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cron_expression");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("environment");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset?>("LastOccurrenceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_occurrence_utc");

                    b.Property<string>("MissPolicy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("miss_policy");

                    b.Property<DateTimeOffset?>("NextOccurrenceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_occurrence_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .IsUnicode(true)
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("TargetKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_key");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("target_type");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled", "NextOccurrenceUtc");

                    b.HasIndex("WorkspaceId", "Environment", "Key")
                        .IsUnique();

                    b.ToTable("schedule_definition", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Scheduling.ScheduleOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<Guid?>("DispatchedRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispatched_run_id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<DateTimeOffset>("OccurrenceUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurrence_utc");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId", "OccurrenceUtc")
                        .IsUnique();

                    b.ToTable("schedule_occurrence", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Tenancy.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan_code");

                    b.Property<DateTimeOffset?>("PurgeAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purge_after");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("citext")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(1000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("suspension_reason");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tenant", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.Tenancy.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("KillSwitchEngaged")
                        .HasColumnType("boolean")
                        .HasColumnName("kill_switch_engaged");

                    b.Property<DateTimeOffset?>("KillSwitchEngagedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kill_switch_engaged_at");

                    b.Property<Guid?>("KillSwitchEngagedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("kill_switch_engaged_by");

                    b.Property<string>("KillSwitchReason")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("kill_switch_reason");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("citext")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantIdentifier")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("TenantIdentifier");

                    b.HasIndex("TenantIdentifier", "Slug")
                        .IsUnique();

                    b.ToTable("workspace", (string)null);
                });

            modelBuilder.Entity("OptimizeAll.Domain.AgentCatalog.AgentDefinition", b =>
                {
                    b.OwnsMany("OptimizeAll.Domain.AgentCatalog.KpiDefinition", "Kpis", b1 =>
                        {
                            b1.Property<Guid>("AgentDefinitionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Direction")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("direction");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .IsUnicode(true)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name");

                            b1.Property<string>("Key")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("key");

                            b1.Property<decimal?>("Target")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("target");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(50)
                                .IsUnicode(true)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("unit");

                            b1.HasKey("AgentDefinitionId", "Id");

                            b1.ToTable("agent_kpi", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AgentDefinitionId");
                        });

                    b.OwnsMany("OptimizeAll.Domain.AgentCatalog.ToolGrant", "ToolGrants", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AgentDefinitionId")
                                .HasColumnType("uuid")
                                .HasColumnName("agent_definition_id");

                            b1.Property<string>("ConstraintsJson")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .IsUnicode(true)
                                .HasColumnType("jsonb")
                                .HasColumnName("constraints");

                            b1.Property<string>("RiskClass")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("risk_class");

                            b1.Property<string>("ToolKey")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("tool_key");

                            b1.HasKey("Id");

                            b1.HasIndex("AgentDefinitionId", "ToolKey")
                                .IsUnique();

                            b1.ToTable("agent_tool_grant", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AgentDefinitionId");
                        });

                    b.Navigation("Kpis");

                    b.Navigation("ToolGrants");
                });

            modelBuilder.Entity("OptimizeAll.Domain.Execution.AgentRun", b =>
                {
                    b.OwnsMany("OptimizeAll.Domain.Execution.AgentRunStep", "Steps", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AgentRunId")
                                .HasColumnType("uuid")
                                .HasColumnName("agent_run_id");

                            b1.Property<string>("ContentJson")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .IsUnicode(true)
                                .HasColumnType("jsonb")
                                .HasColumnName("content");

                            b1.Property<int>("LatencyMilliseconds")
                                .HasColumnType("integer")
                                .HasColumnName("latency_ms");

                            b1.Property<DateTimeOffset>("OccurredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("occurred_at");

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer")
                                .HasColumnName("sequence");

                            b1.Property<string>("StepType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("step_type");

                            b1.Property<long>("Tokens")
                                .HasColumnType("bigint")
                                .HasColumnName("tokens");

                            b1.HasKey("Id");

                            b1.HasIndex("AgentRunId", "Sequence")
                                .IsUnique();

                            b1.ToTable("agent_run_step", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AgentRunId");
                        });

                    b.OwnsOne("OptimizeAll.Domain.Execution.RunBudgetLedger", "Budget", b1 =>
                        {
                            b1.Property<Guid>("AgentRunId")
                                .HasColumnType("uuid");

                            b1.Property<long>("CompletionTokens")
                                .HasColumnType("bigint")
                                .HasColumnName("completion_tokens");

                            b1.Property<decimal>("CostAmount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("cost_amount");

                            b1.Property<string>("CostCurrency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(true)
                                .HasColumnType("character(3)")
                                .HasColumnName("cost_currency")
                                .IsFixedLength();

                            b1.Property<int>("IterationCount")
                                .HasColumnType("integer")
                                .HasColumnName("iteration_count");

                            b1.Property<long>("PromptTokens")
                                .HasColumnType("bigint")
                                .HasColumnName("prompt_tokens");

                            b1.Property<int>("ToolCallCount")
                                .HasColumnType("integer")
                                .HasColumnName("tool_call_count");

                            b1.HasKey("AgentRunId");

                            b1.ToTable("agent_run");

                            b1.WithOwner()
                                .HasForeignKey("AgentRunId");
                        });

                    b.OwnsMany("OptimizeAll.Domain.Execution.ToolInvocation", "ToolInvocations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AgentRunId")
                                .HasColumnType("uuid")
                                .HasColumnName("agent_run_id");

                            b1.Property<Guid?>("ApprovalRequestId")
                                .HasColumnType("uuid")
                                .HasColumnName("approval_request_id");

                            b1.Property<string>("ArgumentsJson")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .IsUnicode(true)
                                .HasColumnType("jsonb")
                                .HasColumnName("arguments");

                            b1.Property<DateTimeOffset?>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at");

                            b1.Property<string>("DenialReason")
                                .HasMaxLength(2000)
                                .IsUnicode(true)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("denial_reason");

                            b1.Property<int?>("DurationMilliseconds")
                                .HasColumnType("integer")
                                .HasColumnName("duration_ms");

                            b1.Property<string>("IdempotencyKey")
                                .HasMaxLength(200)
                                .IsUnicode(true)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("idempotency_key");

                            b1.Property<DateTimeOffset>("RequestedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("requested_at");

                            b1.Property<string>("ResultJson")
                                .HasMaxLength(4000)
                                .IsUnicode(true)
                                .HasColumnType("jsonb")
                                .HasColumnName("result");

                            b1.Property<string>("RiskClass")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("risk_class");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("status");

                            b1.Property<string>("ToolKey")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("tool_key");

                            b1.HasKey("Id");

                            b1.HasIndex("AgentRunId");

                            b1.ToTable("tool_invocation", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AgentRunId");
                        });

                    b.Navigation("Budget")
                        .IsRequired();

                    b.Navigation("Steps");

                    b.Navigation("ToolInvocations");
                });

            modelBuilder.Entity("OptimizeAll.Domain.Governance.ApprovalPolicy", b =>
                {
                    b.OwnsMany("OptimizeAll.Domain.Governance.ApprovalRule", "Rules", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<TimeSpan>("Expiry")
                                .HasColumnType("interval")
                                .HasColumnName("expiry");

                            b1.Property<Guid>("PolicyId")
                                .HasColumnType("uuid")
                                .HasColumnName("policy_id");

                            b1.Property<int>("RequiredApproverCount")
                                .HasColumnType("integer")
                                .HasColumnName("required_approver_count");

                            b1.Property<string>("RequiredRoleKey")
                                .IsRequired()
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("required_role_key");

                            b1.Property<string>("RiskClass")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("risk_class");

                            b1.Property<string>("ToolKey")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("tool_key");

                            b1.HasKey("Id");

                            b1.HasIndex("PolicyId");

                            b1.ToTable("approval_rule", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PolicyId");

                            b1.OwnsOne("OptimizeAll.Domain.Common.Money", "ThresholdAmount", b2 =>
                                {
                                    b2.Property<Guid>("ApprovalRuleId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(19, 4)
                                        .HasColumnType("numeric(19,4)")
                                        .HasColumnName("threshold_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .IsUnicode(true)
                                        .HasColumnType("character(3)")
                                        .HasColumnName("threshold_currency")
                                        .IsFixedLength();

                                    b2.HasKey("ApprovalRuleId");

                                    b2.ToTable("approval_rule");

                                    b2.WithOwner()
                                        .HasForeignKey("ApprovalRuleId");
                                });

                            b1.Navigation("ThresholdAmount");
                        });

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("OptimizeAll.Domain.Governance.ApprovalRequest", b =>
                {
                    b.OwnsMany("OptimizeAll.Domain.Governance.ApprovalDecision", "Decisions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("ApprovalRequestId")
                                .HasColumnType("uuid")
                                .HasColumnName("approval_request_id");

                            b1.Property<Guid>("ApproverUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("approver_user_id");

                            b1.Property<DateTimeOffset>("DecidedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("decided_at");

                            b1.Property<string>("Decision")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("decision");

                            b1.Property<string>("Rationale")
                                .HasMaxLength(4000)
                                .IsUnicode(true)
                                .HasColumnType("character varying(4000)")
                                .HasColumnName("rationale");

                            b1.Property<bool>("StepUpVerified")
                                .HasColumnType("boolean")
                                .HasColumnName("step_up_verified");

                            b1.HasKey("Id");

                            b1.HasIndex("ApprovalRequestId", "ApproverUserId")
                                .IsUnique();

                            b1.ToTable("approval_decision", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ApprovalRequestId");
                        });

                    b.OwnsOne("OptimizeAll.Domain.Common.Money", "EstimatedCost", b1 =>
                        {
                            b1.Property<Guid>("ApprovalRequestId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("estimated_cost_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(true)
                                .HasColumnType("character(3)")
                                .HasColumnName("estimated_cost_currency")
                                .IsFixedLength();

                            b1.HasKey("ApprovalRequestId");

                            b1.ToTable("approval_request");

                            b1.WithOwner()
                                .HasForeignKey("ApprovalRequestId");
                        });

                    b.Navigation("Decisions");

                    b.Navigation("EstimatedCost");
                });

            modelBuilder.Entity("OptimizeAll.Domain.Knowledge.KnowledgeChunk", b =>
                {
                    b.HasOne("OptimizeAll.Domain.Knowledge.KnowledgeDocument", null)
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OptimizeAll.Domain.Notifications.Notification", b =>
                {
                    b.OwnsMany("OptimizeAll.Domain.Notifications.ChannelDelivery", "Deliveries", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("AttemptCount")
                                .HasColumnType("integer")
                                .HasColumnName("attempt_count");

                            b1.Property<string>("Channel")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("channel");

                            b1.Property<DateTimeOffset?>("DeliveredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("delivered_at");

                            b1.Property<bool>("IsDelivered")
                                .HasColumnType("boolean")
                                .HasColumnName("is_delivered");

                            b1.Property<string>("LastError")
                                .HasMaxLength(2000)
                                .IsUnicode(true)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("last_error");

                            b1.Property<Guid>("NotificationId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("NotificationId");

                            b1.ToTable("notification_delivery", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("NotificationId");
                        });

                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("OptimizeAll.Domain.Orchestration.WorkflowRun", b =>
                {
                    b.OwnsMany("OptimizeAll.Domain.Orchestration.WorkTask", "Tasks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid?>("AgentRunId")
                                .HasColumnType("uuid")
                                .HasColumnName("agent_run_id");

                            b1.Property<string>("AssignedAgentKey")
                                .HasMaxLength(100)
                                .IsUnicode(true)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("assigned_agent_key");

                            b1.Property<int>("AttemptCount")
                                .HasColumnType("integer")
                                .HasColumnName("attempt_count");

                            b1.Property<string>("BlockedReason")
                                .HasMaxLength(2000)
                                .IsUnicode(true)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("blocked_reason");

                            b1.Property<DateTimeOffset?>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at");

                            b1.Property<DateTimeOffset?>("HeartbeatAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("heartbeat_at");

                            b1.Property<string>("InputJson")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .IsUnicode(true)
                                .HasColumnType("jsonb")
                                .HasColumnName("input");

                            b1.Property<int>("MaxAttempts")
                                .HasColumnType("integer")
                                .HasColumnName("max_attempts");

                            b1.Property<string>("OutputJson")
                                .HasMaxLength(4000)
                                .IsUnicode(true)
                                .HasColumnType("jsonb")
                                .HasColumnName("output");

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer")
                                .HasColumnName("sequence");

                            b1.Property<DateTimeOffset?>("StartedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("started_at");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("status");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(300)
                                .IsUnicode(true)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("title");

                            b1.Property<Guid>("WorkflowRunId")
                                .HasColumnType("uuid")
                                .HasColumnName("workflow_run_id");

                            b1.HasKey("Id");

                            b1.HasIndex("WorkflowRunId", "Status");

                            b1.ToTable("work_task", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkflowRunId");

                            b1.OwnsMany("OptimizeAll.Domain.Orchestration.TaskDependency", "Dependencies", b2 =>
                                {
                                    b2.Property<Guid>("TaskId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("task_id");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<Guid>("DependsOnTaskId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("depends_on_task_id");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasMaxLength(30)
                                        .HasColumnType("character varying(30)")
                                        .HasColumnName("dependency_type");

                                    b2.HasKey("TaskId", "Id");

                                    b2.HasIndex("TaskId", "DependsOnTaskId")
                                        .IsUnique();

                                    b2.ToTable("task_dependency", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("TaskId");
                                });

                            b1.Navigation("Dependencies");
                        });

                    b.OwnsOne("OptimizeAll.Domain.Common.Money", "ActualCost", b1 =>
                        {
                            b1.Property<Guid>("WorkflowRunId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("actual_cost_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(true)
                                .HasColumnType("character(3)")
                                .HasColumnName("actual_cost_currency")
                                .IsFixedLength();

                            b1.HasKey("WorkflowRunId");

                            b1.ToTable("workflow_run");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowRunId");
                        });

                    b.OwnsOne("OptimizeAll.Domain.Common.Money", "EstimatedCost", b1 =>
                        {
                            b1.Property<Guid>("WorkflowRunId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("estimated_cost_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(true)
                                .HasColumnType("character(3)")
                                .HasColumnName("estimated_cost_currency")
                                .IsFixedLength();

                            b1.HasKey("WorkflowRunId");

                            b1.ToTable("workflow_run");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowRunId");
                        });

                    b.Navigation("ActualCost")
                        .IsRequired();

                    b.Navigation("EstimatedCost");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("OptimizeAll.Domain.Tenancy.Workspace", b =>
                {
                    b.OwnsOne("OptimizeAll.Domain.Common.Money", "MonthlyBudgetCap", b1 =>
                        {
                            b1.Property<Guid>("WorkspaceId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("budget_cap_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .IsUnicode(true)
                                .HasColumnType("character(3)")
                                .HasColumnName("budget_cap_currency")
                                .IsFixedLength();

                            b1.HasKey("WorkspaceId");

                            b1.ToTable("workspace");

                            b1.WithOwner()
                                .HasForeignKey("WorkspaceId");
                        });

                    b.Navigation("MonthlyBudgetCap")
                        .IsRequired();
                });

            modelBuilder.Entity("OptimizeAll.Domain.Knowledge.KnowledgeDocument", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
